타이타닉 데이터는 머신러닝의 교과서와 같은 데이터셋입니다. 정말 많이 사용됩니다.

우선 타이타닉 데이터를 살펴보겠습니다.

승객 891명, 컬럼 12개입니다.

### 데이터 기본 정보

**표 컬럼 기본 정보**


| 컬럼 | 뜻 |
|---|---|
| `PassengerId` | 승객 번호 |
| `Survived` | **생존 여부 (정답)** — 0=사망, 1=생존 |
| `Pclass` | 객실 등급 (1 / 2 / 3) |
| `Name` | 이름 |
| `Sex` | 성별 |
| `Age` | 나이 |
| `SibSp` | 함께 탄 형제자매 + 배우자 수 |
| `Parch` | 함께 탄 부모 + 자녀 수 |
| `Ticket` | 티켓 번호 |
| `Fare` | 요금 |
| `Cabin` | 객실 번호 |
| `Embarked` | 탑승 항구 (C / Q / S) |

In [1]:
import pandas as pd

df = pd.read_csv("Titanic-Dataset.csv")

df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

보다시피 일반적으로 승객의 데이터들을 토대로 생존률을 예측하는 식으로 많이 활용됩니다.

하지만 이미 발생한 사건에 대한 데이터이기 때문에, 예측 자체보다 어떤 사람이 살아남았는가를 설명하는걸 목표로 분석을 해보도록 하겠습니다.

머신러닝 분석을 수행하기 전에는 먼저 **평가 지표**를 설정하는 것이 무엇보다 중요합니다. 서비스 유형, 라벨 균형 등 여러가지 요소를 고려해서 신중하게 결정해야 하는 요소이기도 하죠.

일단 지금은 처음이니 '정확도' 지표를 토대로 진행을 하도록 하겠습니다. 평가지표의 중요성에 대해선 뒤의 '분류' 단원에서 다시 자세히 다뤄 보도록 하겠습니다.

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

**[Dtype]**

int64는 정수형, float64는 실수형, object는 문자열이라는 것을 나타냅니다.

**[Non-Null Count]**

각 컬럼에 비어 있지 않은 값의 수를 보여줍니다.
이걸 보면 지금 'Age', 'Cabin', 'Embarked' 컬럼 각각에 결측치가 있다는 것을 알 수 있습니다.

정확하게 결측치를 확인하려면 아래와 같이 확인할 수 있습니다.

In [3]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

간단하게 주어진 데이터를 이용해 머신러닝 모델을 학습시켜 보겠습니다.

정답 컬럼은 'Survived'이고, 나머지 컬럼들을 예측 컬럼으로 분리합니다.

In [4]:
y = df['Survived']
X = df.drop(columns=['Survived'])

print(X.shape, y.shape)
print("X :")
print(X.head())
print("y :")
print(y.head())

(891, 11) (891,)
X :
   PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...
2            3       3                             Heikkinen, Miss. Laina
3            4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4            5       3                           Allen, Mr. William Henry

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S
1  female  38.0      1      0          PC 17599  71.2833   C85        C
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
3  female  35.0      1      0            113803  53.1000  C123        S
4    male  35.0      0      0            373450   8.0500   NaN        S
y :
0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

이걸 바로 모델에 입력해 보겠습니다.

In [5]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(random_state=42)
model.fit(X, y)   # ValueError 발생

ValueError: could not convert string to float: 'Braund, Mr. Owen Harris'

에러가 발생합니다.

"could not convert string to float: 'Braund, Mr. Owen Harris'"

문자열을 정수형으로 변환할 수 없다는 뜻입니다. 무슨 의미냐면, 머신러닝 모델은 데이터를 계산하기 위해 숫자를 입력 받아야 하는데, 문자열을 입력 받아서 생긴 문제입니다.

여기서 저흰 문자열은 머신러닝 모델에 입력하지 못한다는 걸 알 수 있죠.

그러면 문자열은 어떻게 처리할까요? 보통은 제외하거나, 숫자로 변형해서 입력하게 됩니다.

지금 문자열로 이루어진 컬럼이 뭐뭐 있죠?

In [6]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Pclass       891 non-null    int64
 2   Name         891 non-null    object
 3   Sex          891 non-null    object
 4   Age          714 non-null    float64
 5   SibSp        891 non-null    int64
 6   Parch        891 non-null    int64
 7   Ticket       891 non-null    object
 8   Fare         891 non-null    float64
 9   Cabin        204 non-null    object
 10  Embarked     889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 76.7+ KB

Name, Sex, Ticket, Cabin, Embarked 5개의 컬럼이 문자열입니다. 각각 데이터도 확인해 보면...

In [7]:
df[["Name", "Sex", "Ticket", "Cabin", "Embarked"]].head()

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S

이 중에서 어떤 컬럼을 숫자로 바꿔서 유지하고, 어떤 컬럼은 모델 학습에 불필요할까요?

각자의 의견을 적어봅시다. (아래 셀을 보지 말고 적어 보세요)

* 넣어야 하는 것: []
* 이유 : 
* 빼야 하는 것 : []
* 이유 :

---

### 데이터 전처리

In [8]:
X = X.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'])
X['Sex'] = X['Sex'].map({'male': 0, 'female': 1})
X['Embarked'] = X['Embarked'].map({'S': 1, 'C': 2, 'Q': 3})

X.head()

   Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0       3    0  22.0      1      0   7.2500       1.0
1       1    1  38.0      1      0  71.2833       2.0
2       3    1  26.0      0      0   7.9250       1.0
3       1    1  35.0      1      0  53.1000       1.0
4       3    0  35.0      0      0   8.0500       1.0

이제 문자열을 모두 처리했으니 학습이 가능할까요?

In [ ]:
model = LogisticRegression(random_state=42)
model.fit(X, y)

ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

또 에러가 떴죠?

"Input X contains NaN."

이건 결측치(NaN)가 데이터에 포함되어 있어 계산이 불가능하다는 것을 의미합니다.

이런 식으로 결측치가 있으면 학습하지 못하는 경우가 많기 때문에 대부분 머신러닝 모델을 학습하기 전에는 결측치를 꼭 없애고 학습을 하는게 좋습니다. (DecisionTree와 같은 의사결정나무 모델은 결측치가 있어도 학습이 되기는 합니다.)

결측치의 처리 방법으로는,
* 행 삭제 : 결측치가 있는 승객 정보를 제외하는 방법.
* 열 제외 : 결측치가 있는 컬럼을 제외하는 방법.
* 값 채우기 : 해당 데이터를 유지하면서, 실제와 다른 값으로 채워 넣는다.

결측치를 어떻게 처리하느냐에 따라서도 머신러닝 모델의 결과가 많이 달라지게 됩니다.

In [ ]:
X.isna().sum()

Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

우선 지금은 Age 컬럼은 Age 컬럼의 중앙값, Embarked 컬럼은 최빈값으로 채워 넣도록 하겠습니다.

In [9]:
X['Age'] = X['Age'].fillna(X['Age'].median())
X['Embarked'] = X['Embarked'].fillna(X['Embarked'].mode()[0])

X.isna().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

이번에야 말로 학습을 해볼 수 있을까요?

In [10]:
model = LogisticRegression(random_state=42)
model.fit(X, y)

c:\Users\rando\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(random_state=42)

드디어 학습이 되었습니다! 성능을 한번 확인해 볼까요? 정확도를 한번 측정해 보겠습니다.

In [11]:
model.score(X, y)

0.8013468013468014

80%의 정확도를 달성했습니다!

그럼 여기서 물어보겠습니다.

80%는 좋은 정확도인가요?

만약 모든 사람들의 생존 여부를 '사망'으로 예측한다면 모델의 정확도는 어떻게 나타날까요?

In [ ]:
print(f"모두 사망으로 예측한 정확도: {(y == 0).mean():.1%}")

모두 사망으로 예측한 정확도: 61.6%

이렇게 아무런 승객 정보를 활용하지 않아도 61%의 정확도가 나옵니다. 그렇다면 우리 모델의 80%는 이 기준보다는 꽤 나아졌다고 볼 수 있겠죠?

여기서 한 가지 더 생각해보면 좋은 것이 있습니다. 이 80%는 저희가 학습한 데이터를 다시 예측해서 얻은 정확도라는 것입니다.

쉽게 말하면 미리 답지를 본 적이 있는 문제를 푼 거란 얘깁니다. 그렇다면 만약 이 모델을 이용해서 선박의 승객 생존률을 나중에 예측하고자 한다면 어떤 문제가 생길까요?

---

그래서 학습용 데이터와 평가용 데이터를 나눠서 모델 예측을 수행하게 됩니다.

학습용 데이터는 모델이 학습할 때 보는 데이터, 평가용 데이터는 모델이 학습할 때 보지 못한 데이터.

이렇게 나눠야 모델이 새로운 데이터를 만났을 때도 잘 맞추는지를 확인할 수 있는거죠.

In [14]:
from sklearn.model_selection import train_test_split

df = pd.read_csv("Titanic-Dataset.csv")

y = df['Survived']
X = df.drop(columns=['Survived'])

X = X.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'])
X['Sex'] = X['Sex'].map({'male': 0, 'female': 1})
X['Embarked'] = X['Embarked'].map({'S': 1, 'C': 2, 'Q': 3})

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

# 결측치를 처리할 때 사용했던 결측치 처리를 다시 나눠서 수행합니다.
X_train['Age'] = X_train['Age'].fillna(X_train['Age'].median())
X_train['Embarked'] = X_train['Embarked'].fillna(X_train['Embarked'].mode()[0])

X_test['Age'] = X_test['Age'].fillna(X_train['Age'].median())
X_test['Embarked'] = X_test['Embarked'].fillna(X_train['Embarked'].mode()[0])

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(712, 7)
(179, 7)
(712,)
(179,)

다시, 훈련셋으로 모델을 훈련하고 테스트셋으로 모델 성능을 예측해 보겠습니다.

In [15]:
model = LogisticRegression(random_state=42)
model.fit(X_train, y_train)

model.score(X_test, y_test)

c:\Users\rando\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.8044692737430168

처음 본 데이터에 대해서도 80%의 정확도를 달성하네요. 앞의 결과보다 좀 더 신빈성 있는 결과를 얻은 것 같습니다.

한 번 직접 값을 입력해서 해당 승객의 생존 여부 예측 결과를 받아 봅시다.

In [ ]:
X_train.head()

     Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
659       1    0  58.0      0      2  113.2750       2.0
188       3    0  40.0      1      1   15.5000       3.0
251       3    1  29.0      1      1   10.4625       1.0
339       1    0  45.0      0      0   35.5000       1.0
308       2    0  30.0      1      0   24.0000       2.0

In [ ]:
# 아래 값을 바꿔가면서 실행해 보세요
new_customer = pd.DataFrame([{
    "Pclass": 0,
    "Sex": 0,
    "Age": 0,
    "SibSp": 0,
    "Parch": 0,
    "Fare": 0,
    "Embarked": 0
}])

# 앞에서 선택한 입력 열과 같은 순서로 모델에 전달합니다.
new_prediction = model.predict(new_customer)[0]
print("모델의 예측:", {0: "사망", 1: "생존"}[new_prediction])

모델의 예측: 생존